# Usar dentro de P2 (cd P2)
PACKS = trayectos

all:
	javac -Werror $(PACKS)/*.java

doc:
	javadoc -d doc $(PACKS)/*.java

run:
	java trayectos/MainTrayectos
	# Annadir mas

clean:
	rm $(PACKS)/*.class